module.exports = [
  {
    id: "AM1",
    name: "Cheesy Chorizo and Beef Burger",
    subheading: "with salad and sweet potato fries",
    image: "../assets/images/AM1_cheesy_chorizo_and_beef_burger.jpg",
    rating: "-",
    ingredients: [
      ["ingredient_brioche_buns", 1, "unit(s)"],
      ["ingredient_chorizo", 50, "grams"],
      ["ingredient_beef_mince", 125, "grams"],
      ["ingredient_grated_cheese", 25, "grams"],
      ["ingredient_aioli", 1, "tbsp"],
      ["ingredient_paprika", 2, "tsp"],
      ["ingredient_breadcrumbs", 1, "cup"],
      ["ingredient_salad_leaves", 20, "grams"],
      ["ingredient_balsamic_glaze", 1, "tbsp"],
      ["ingredient_sweet_potato", 1, "unit(s)"],
      ["ingredient_onion", 0.5, "unit(s)"],
      ["ingredient_tomato", 0.5, "unit(s)"],
    ],
    total_time: "25",
    cooking_time: "30",
    calories: "1123",
    difficulty: "Easy",
    description:
      "The juicy cheeseburger contains both beef and chorizo, for a meal that's mighty meaty. A paprika aioli and sweet potato fries accompany, along with a fresh side salad for a hint of health.",
    link: "https://drive.google.com/file/d/1N2clbWGdHkPmnV18lByrToHxvvV4On06/view?usp=sharing",
    tags: ["Burger", "Chips", "Fake Fast Food", "Beef", "Chorizo"],
    meal: ["Lunch", "Dinner"],
    cuisine: "American",
  },
];
